### ISSUE TITLE
How to connect to database in config.php

### ISSUE THREAD

**Issue by rszczypka** [cmourizard/sugar-docker-example#1]
Hi,
this is my `docker-compose.yml`:

```
web:
    container_name: web
    build: ./images/php5.4-apache
    ports:
        - 51515:80
    links:
        - db
        - search        
    volumes:
        - /home/rafal/docker/sugar-docker-example/data/web:/var/www/html
db:
    container_name: db
    image: percona:5.6
    environment:
        - MYSQL_ROOT_PASSWORD=root
    ports:
        - 3307:3306
    volumes:
        - /home/rafal/docker/sugar-docker-example/data/mysql:/var/lib/mysql
search:
    container_name: search
    image: elasticsearch:1.4
    ports:
        - 9201:9200
        - 9301:9300
```

What should I put into config.php to connect to my database?
